foother/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/<str:username>', views.update, name='update'),
    path('<str:username>/', views.detail, name='detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/<str:username>/', views.follow, name='follow'),
]

foother/foother/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.foother_index, name='foother-index'),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('maps.urls')),
    path('foods/', include('foods.urls')),
    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foother/maps/urls.py
from django.urls import path
from . import views


app_name = 'maps'


urlpatterns = [
    path('all/', views.review_all, name='review-all'),
    path('create/', views.review_create, name='review-create'),
    path('<str:username>/<int:review_pk>/', views.review_detail, name='review-detail'),
    path('<int:review_pk>/update/', views.review_update, name='review-update'),
    path('<int:review_pk>/like/', views.like, name='like'),
    path('<str:comment_user_pk>/<int:review_pk>/comment/create/', views.comment_create, name='comment-create'),
    path('<str:comment_username>/<int:review_pk>/comment/complete/', views.comment_complete, name='comment-complete'),
]

foother/foother/views.py
from django.shortcuts import render
from foods.models import FoodCategory
# from django.core.paginator import Paginator
from django.contrib.auth import get_user_model


def user_ranking():
    User = get_user_model()
    users = User.objects.all()
    if len(users) >3:
        while len(users) == 3:
            del users[-1]
    
    ranking = {
        'ranking' : users,
    }
    # return User.objects.all()
    return ranking
    # rankings = user_ranking()


def foother_index(request):
    rankings = user_ranking()
    foodsCategories = FoodCategory.objects.all()
    # emotion = Emotion.objects.get(name=Food.food_name).emotion
    # foods = emotion.food_set.all()

    context = {
        'foodsCategories' : foodsCategories,
        'rankings' : rankings
        # 'foods' : foods
    }
    return render(request,'foods/food_main.html', context)

#동규오빠 랭킹
# def make_users():
#     User = get_user_model()
#     users = User.objects.all()
#     if len(users) >5:
#         while len(users) == 5:
#             del users[-1]
    
#     context = {
#         'users' : users,
#     }
#     # return User.objects.all()
#     return context

# def ???(reuqest):
#     users = User.objects.all()
#     if len(users) >5:
#         while len(users) == 5:
#             del users[-1]
    
#     context = {
#         'users' : users,
#     }
#     return render(request, 'base.html', context)

foother/foother/templates/_faq.html
<!-- ======= Resume Section ======= -->
    <section id="faq" class="resume">

      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Resume</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <div class="row">
          <div class="col-lg-6">
            <h3 class="resume-title">Sumary</h3>
            <div class="resume-item pb-0">
              <h4>Brandon Johnson</h4>
              <p><em>Innovative and deadline-driven Graphic Designer with 3+ years of experience designing and developing user-centered digital/print marketing material from initial concept to final, polished deliverable.</em></p>
              <ul>
                <li>Portland par 127,Orlando, FL</li>
                <li>(123) 456-7891</li>
                <li>alice.barkley@example.com</li>
              </ul>
            </div>

            <h3 class="resume-title">Education</h3>
            <div class="resume-item">
              <h4>Master of Fine Arts &amp; Graphic Design</h4>
              <h5>2015 - 2016</h5>
              <p><em>Rochester Institute of Technology, Rochester, NY</em></p>
              <p>Qui deserunt veniam. Et sed aliquam labore tempore sed quisquam iusto autem sit. Ea vero voluptatum qui ut dignissimos deleniti nerada porti sand markend</p>
            </div>
            <div class="resume-item">
              <h4>Bachelor of Fine Arts &amp; Graphic Design</h4>
              <h5>2010 - 2014</h5>
              <p><em>Rochester Institute of Technology, Rochester, NY</em></p>
              <p>Quia nobis sequi est occaecati aut. Repudiandae et iusto quae reiciendis et quis Eius vel ratione eius unde vitae rerum voluptates asperiores voluptatem Earum molestiae consequatur neque etlon sader mart dila</p>
            </div>
          </div>
          <div class="col-lg-6">
            <h3 class="resume-title">Professional Experience</h3>
            <div class="resume-item">
              <h4>Senior graphic design specialist</h4>
              <h5>2019 - Present</h5>
              <p><em>Experion, New York, NY </em></p>
              <ul>
                <li>Lead in the design, development, and implementation of the graphic, layout, and production communication materials</li>
                <li>Delegate tasks to the 7 members of the design team and provide counsel on all aspects of the project. </li>
                <li>Supervise the assessment of all graphic materials in order to ensure quality and accuracy of the design</li>
                <li>Oversee the efficient use of production project budgets ranging from $2,000 - $25,000</li>
              </ul>
            </div>
            <div class="resume-item">
              <h4>Graphic design specialist</h4>
              <h5>2017 - 2018</h5>
              <p><em>Stepping Stone Advertising, New York, NY</em></p>
              <ul>
                <li>Developed numerous marketing programs (logos, brochures,infographics, presentations, and advertisements).</li>
                <li>Managed up to 5 projects or tasks at a given time while under pressure</li>
                <li>Recommended and consulted with clients on the most appropriate graphic design</li>
                <li>Created 4+ design presentations and proposals a month for clients and account managers</li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </section><!-- End Resume Section -->

foother/foother/templates/_foother.html
{% load static %}
<!-- ======= Contact Section ======= -->
    {% comment %} <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Contact</h2>
        </div>

        <div class="row mt-1">

          <div class="col-lg-4">
            <div class="info">
              <div class="address">
                <i class="icofont-google-map"></i>
                <h4>Location:</h4>
                <p>A108 Adam Street, New York, NY 535022</p>
              </div>

              <div class="email">
                <i class="icofont-envelope"></i>
                <h4>Email:</h4>
                <p>info@example.com</p>
              </div>

              <div class="phone">
                <i class="icofont-phone"></i>
                <h4>Call:</h4>
                <p>+1 5589 55488 55s</p>
              </div>

            </div>

          </div>

          <div class="col-lg-8 mt-5 mt-lg-0">

            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="form-row">
                <div class="col-md-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                  <div class="validate"></div>
                </div>
                <div class="col-md-6 form-group">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                  <div class="validate"></div>
                </div>
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                <div class="validate"></div>
              </div>
              <div class="form-group">
                <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                <div class="validate"></div>
              </div>
              <div class="mb-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
              </div>
              <div class="text-center"><button type="submit">Send Message</button></div>
            </form>

          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main --> {% endcomment %}

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h4>지혜 영기 동규</h4>
      <div class="social-links">
        <a href="https://jihyehaley.github.io" class="twitter"><i class="bx bxl-github"></i></a>
        <a href="https://github.com/ee249" class="twitter"><i class="bx bxl-github"></i></a>
        <a href="https://github.com/dongkyu92" class="twitter"><i class="bx bxl-github"></i></a>
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>MyResume</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: [license-url] -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/ -->
        Edited by <a href="jihyehaley.github.io">Jihye Oh (Haley)</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="bx bx-up-arrow-alt"></i></a>
  <div id="preloader"></div>
  </div>

foother/foother/templates/_main.html
<!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex flex-column justify-content-center">
    
  </section><!-- End Hero -->


  

foother/foother/templates/_members.html
{% load static %}
<!-- ======= Testimonials Section ======= -->
    <section id="member" class="testimonials section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>만든 사람들</h2>
        </div>

        <div class="owl-carousel testimonials-carousel" data-aos="zoom-in" data-aos-delay="100">

          <div class="testimonial-item">
            <img src="{% static 'img/member/jihye.png' %}" class="member-img" alt="">
            <h3>Jihye Oh 지혜</h3>
            <h4>Designer, Back-End</h4>
            <h4>Almost &amp; Founder... HAHAHAHA</h4>
            <p>
              <i class="bx bxs-quote-alt-left quote-icon-left"></i>
              I'm busy. Do not make me nervous.
              <i class="bx bxs-quote-alt-right quote-icon-right"></i>
            </p>
          </div>

          <div class="testimonial-item">
            <img src="{% static 'img/testimonials/testimonials-2.jpg' %}" class="member-img" alt="">
            <h3>Chuck D.K. Kim 동규</h3>
            <h4>Back-End Enginer and KakaoAPI Master</h4>
            <p>
              <i class="bx bxs-quote-alt-left quote-icon-left"></i>
              Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.
              <i class="bx bxs-quote-alt-right quote-icon-right"></i>
            </p>
          </div>

          <div class="testimonial-item">
            <img src="{% static 'img/testimonials/testimonials-3.jpg' %}" class="member-img" alt="">
            <h3>Jena Karlis</h3>
            <h4>Back-End Enginer and a Mashroom🍄</h4>
            <p>
              <i class="bx bxs-quote-alt-left quote-icon-left"></i>
              Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim tempor labore quem eram duis noster aute amet eram fore quis sint minim.
              <i class="bx bxs-quote-alt-right quote-icon-right"></i>
            </p>
          </div>

        </div>

      </div>
    </section><!-- End Testimonials Section -->

foother/foother/templates/_nav.html
{% load static %}

<!-- ======= Header ======= -->
  <header id="header" class="mt-2" >
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.1/css/all.css" integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q" crossorigin="anonymous">
    <div class="nav-logo-title" data-aos="zoom-in" data-aos-delay="10">
      <a href="{% url 'foother-index' %}" style="color:black"><h1><span class="typed text-center" 
      data-typed-items="오늘은, 뭐먹지?"></span></h1><a>
      {% comment %}<div class="social-links"> {% endcomment %}
      {% comment %} <a href="#" class="twitter"><i class="bx bxl-github"></i></a> {% endcomment %}
    </div>
    <div class="text-left ml-3 mt-2 mb-2">
      {% if request.user.is_authenticated %}
          <a href="{% url 'accounts:profile' request.user.username %}" style="color:black; font-size:1.4rem">
          <img src="{{ request.user.user_profile_image.url }}" class="rounded-circle nav-user-icon mr-1">
          {{ request.user }}</a>
      {% else %}
    <div class="text-center mt-4 mb-4">
            <a href="{% url 'accounts:signup'%}" ><img src="{% static 'img/nav/signup.png' %}" class="nav-sign-icon mr-2 ml-2"></a>
            <a href="{% url 'accounts:login'%}" ><img src="{% static 'img/nav/login.png' %}" class="nav-sign-icon mr-2 ml-2"></a>
            {% comment %} <a href="{% url 'accounts:signup'%}" data-toggle="modal" data-target="#signup">회원가입</a>
            <a href="{% url 'accounts:login'%}" data-toggle="modal" data-target="#login">로그인</a>
            {% include 'accounts/form.html' %} {% endcomment %}
      {% endif %}
    </div>
 
    <nav class="nav-menu d-flex flex-column justify-content-flex-start">
      <ul>
        {% comment %} <i class="bx bx-book-content mr-2 ml-2"></i> {% endcomment %}
        <li><a href="{% url 'maps:review-all' %}"><img src="{% static 'img/nav/all.png' %}" class="nav-icon mr-2 ">전체보기</a></li>
        <li><a href="{% url 'foother-index' %}"><img src="{% static 'img/nav/foodrec.png' %}" class="nav-icon mr-2 ">음식추천</a></li>
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'maps:review-create' %}"><img src="{% static 'img/nav/upload.png' %}" class="nav-icon mr-2 ">업로드</a></li>
        <li><a href="{% url 'accounts:profile' request.user.username  %}"><img src="{% static 'img/nav/profile.png' %}" class="nav-icon mr-2">프로필</a></li>
        {% endif %}
        {% comment %} <li><a><i class="bx bx-server mr-2 ml-2"></i>전체보기</a></li> {% endcomment %}
        {% comment %} <li><a ><i class="bx bx-envelope mr-2 ml-2"></i>FAQ</a></li> {% endcomment %}
      {% if request.user.is_authenticated %}
        <li><a href="{% url 'accounts:logout' %}"><img src="{% static 'img/nav/logout.png' %}" class="nav-icon mr-2 ">로그아웃</a></li>
      {% endif %}
      </ul>
    </nav><!-- .nav-menu -->
      {% comment %} <div class="ml-3">
        <p class="ml-2" style="font-size:1.2em; font-weight:500"><i class="fas fa-crown fa-xs mr-1" style="color:#f5da42"></i>유저 랭킹<i class="fas fa-crown fa-xs ml-1" style="color:#f5da42"></i></p>
          {% for user in rankings %}
            <div class="d-block"> 
              <span style="font-size:1.1em">
                {{ forloop.counter }}등:
                {{ user }}님
              </span>
            </div>   
          {% endfor %}
      </div>    {% endcomment %}
              
           
    

  </header><!-- End Header -->

foother/foother/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Foother</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- bootstrap cdn-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">  
  
  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  {% comment %} <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon"> {% endcomment %}
  
  <!-- kakaomap api-->
  <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=50be581e2ca72229d9d9ae0b3a47c26c&libraries=services"></script>
  
  <!-- Google Fonts -->
  {% comment %} <link href="https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap" rel="stylesheet"> {% endcomment %}
  <link href="https://fonts.googleapis.com/css2?family=Gaegu:wght@400;700&display=swap" rel="stylesheet">
  {% comment %} <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet"> {% endcomment %}
  {% comment %} <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Noto+Sans+KR:wght@300;400;500&display=swap" rel="stylesheet"> {% endcomment %}

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">


  <!-- Template Main CSS File -->
  <link href="{% static 'style/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: MyResume - v2.1.0
  * Template URL: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>
  {% include '_nav.html' %}
 <main id="main"> 
  <div class="container2 mt-5 mb-5">
    {% comment %} {% include '_main.html' %} {% endcomment %}
    {% block comment %}
    {% endblock  %}

    {% block content %}
    {% endblock  %}
  </div>
    {% comment %} {% include '_members.html' %} {% endcomment %}
</main>

    {% include '_foother.html' %}
    

  <!-- javascript cdn-->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  
  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'vendor/typed.js/typed.min.js' %}"></script>
  <script src="{% static 'vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>