foother/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/<str:username>', views.update, name='update'),
    path('<str:username>/', views.detail, name='detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/<str:username>/', views.follow, name='follow'),
]

foother/foother/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.foother_index, name='foother-index'),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('maps.urls')),
    path('foods/', include('foods.urls')),
    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foother/maps/urls.py
from django.urls import path
from . import views


app_name = 'maps'


urlpatterns = [
    path('all/', views.review_all, name='review-all'),
    path('create/', views.review_create, name='review-create'),
    path('<str:username>/<int:review_pk>/', views.review_detail, name='review-detail'),
    path('<int:review_pk>/update/', views.review_update, name='review-update'),
    path('<int:review_pk>/like/', views.like, name='like'),
    path('<str:comment_user_pk>/<int:review_pk>/comment/create/', views.comment_create, name='comment-create'),
    path('<str:comment_username>/<int:review_pk>/comment/complete/', views.comment_complete, name='comment-complete'),
]

foother/maps/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class Review(models.Model):
    # hidden
    lat = models.FloatField()
    lng = models.FloatField()
    restaurant_address = models.CharField(max_length=30)

    # TextInput_readonly
    restaurant_name = models.CharField(max_length=30)

    # TextInput
    food_name = models.CharField(max_length=30)
    
    # Textarea
    food_review = models.CharField(max_length=30)
    
    #손봐야할 거
    food_star = models.IntegerField()

    food_image = ProcessedImageField(
                upload_to='upload_photo',
                processors=[ResizeToFill(200, 200)],
                format='JPEG',
                options={
                    'quality': 80}
    )
    
    visit_date = models.DateField(auto_now_add=False)

    food_kind = models.CharField(max_length=10)

    # ForeignKey
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    
    class Meta:
        ordering = ['-id']


class Comment(models.Model):
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='which_review')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='which_user')

    class Meta:
        ordering = ['-created_at']

foother/maps/forms.py
from django import forms
from .models import Review, Comment
from django.forms.widgets import SelectDateWidget

class ReviewForm(forms.ModelForm):
    # hidden tag
    lat = forms.FloatField(
        widget=forms.HiddenInput()
    )
    lng = forms.FloatField(
        widget=forms.HiddenInput()
    )
    restaurant_address = forms.CharField(
        widget=forms.HiddenInput()
    )
    restaurant_name = forms.CharField(
        label = "﹅먹은 장소: ",
        widget=forms.TextInput(
            attrs = {
                'class' : 'my-restaurant-name form-control',
                'placeholder' : '먹은 장소를 입력해주세요',
                'readonly' : '',
            }
        )
    )


    # TextInput
    food_name = forms.CharField(
        label = "﹅먹은 것: ",
        widget = forms.TextInput(
            attrs = {
                'class' : 'my-food-name form-control',
                'placeholder' : '먹은 것을 입력해주세요',
            }
        )
    )

    # Textarea
    food_review = forms.CharField(
        label = '﹅후기: ',
        widget = forms.Textarea(
            attrs = {
                'class' : 'my-food-review form-control',
                'placeholder' : '후기를 입력해주세요',
                'rows' : 4,
                'cols' : 5,
            }
        )
    )

        
    visit_date = forms.DateField(
        label = '﹅방문 날짜: ',
        widget = SelectDateWidget(
            empty_label = ('년', '월', '일',)
        ),
    )

    CHOICES = [
        ('rice', '밥'),
        ('noodle', '면'),
        ('special', '특식'),
        ('soup', '국탕'),
        ('simple', '간편식'),
        ('snack', '분식'),
        ('pot', '찌개'),
        ('bbq', '구이'),
        ('hangover', '해장'),
    ]

    food_kind = forms.ChoiceField(
        choices=CHOICES,
        label = "﹅카테고리:",
        # widget = forms.ChoiceField(
        #     attrs = {
        #         'class' : 'my-food-review',
        #         'placeholder' : '카테고리를 선택해주세요',
        #     }
        # )
    )
    five = 5
    four = 4
    three = 3
    two = 2
    one = 1


    CHOICES_2 = [
        (five, '⭐️⭐️⭐️⭐️⭐️'),
        (four, '⭐️⭐️⭐️⭐️'),
        (three, '⭐️⭐️⭐️'),
        (two, '⭐️⭐️'),
        (one, '⭐️'),
    ]


    food_star = forms.ChoiceField(
        choices=CHOICES_2,
        label = "﹅별점:",
        widget = forms.Select()
        #     attrs = {
        #         'class' : 'my-food-review',
        #         'placeholder' : '카테고리를 선택해주세요',
        #     }
        # )
    )
    
    
    class Meta:
        model = Review
        exclude = ('user', 'like_users')


class CommentForm(forms.ModelForm):
    contents = forms.CharField(
        widget = forms.Textarea(
            attrs={
                'placeholder': '댓글을 써주세요',
                'rows' : 4,
                'cols' : 6,
            }
        )
    )

    class Meta:
        model = Comment
        fields = ['contents']

foother/maps/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ReviewForm, CommentForm
from .models import Review, Comment
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator


def user_ranking():
    User = get_user_model()
    users = User.objects.all()
    if len(users) >3:
        while len(users) == 3:
            del users[-1]
    
    ranking = {
        'ranking' : users,
    }
    # return User.objects.all()
    return ranking
    # rankings = user_ranking()


@login_required
@require_http_methods(['GET', 'POST'])
def review_create(request):
    # user = request.user
    rankings = user_ranking()
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('accounts:profile', review.user.username)

    else:
        form = ReviewForm()
        # key = config('API_KEY')

    context = {
        'form' : form,
        # 'key' : key,
        'rankings' : rankings,
    }
    return render(request, 'maps/review_create.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def review_detail(request, username, review_pk):
    rankings = user_ranking()

    review = Review.objects.get(pk=review_pk)

    comments = Comment.objects.all()
    send_comments = []

    for comment in comments:
        if comment.review_id == review_pk:
            valid_comment = comment
            send_comments.append(valid_comment)

    for send in send_comments:
        print(send.review_id)
        print(send.contents)
        print(send.review.user.username)

    paginator = Paginator(send_comments, 5)
    page_number = request.GET.get('page')
    send_comments = paginator.get_page(page_number)
    
    context = {
        'review' : review,
        'comments' : comments,
        'rankings' : rankings,
        'send_comments' : send_comments,
    }

    return render(request, 'maps/review_detail.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def review_update(request, review_pk):
    rankings = user_ranking()
    review = Review.objects.get(pk=review_pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES, instance=review)
        if form.is_valid():
            review = form.save()
            # (commit=False)
            # review.user = request.user
            # review.save()
            return redirect('maps:review-detail', review.user, review.pk)
    else:
        form = ReviewForm(instance=review)
       
    context = {
        'form' : form,
        'rankings' : rankings,
    }
    return render(request, 'maps/review_update.html', context)



@login_required
def like(request, review_pk):
    
    print(request)
    review = get_object_or_404(Review, pk=review_pk)
    
    print(review)
    user = request.user
    # review.like_users.filter(pk=user.pk).exist():

    if review in user.like_reviews.all():
        user.like_reviews.remove(review)
        liked = False

    else:
        user.like_reviews.add(review)
        liked= True

    context = {
        'msg' : 'like works',
        'liked' : liked,
       
    }

    return JsonResponse(context)


@login_required
def comment_create(request, comment_user_pk, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.method == 'POST':
        print("comment post 들어옴")
        form = CommentForm(request.POST)
        if form.is_valid():
            print("comment post_valid 들어옴")
            comment = form.save(commit=False)
            print(comment)
            comment.review = review
            comment.user = request.user
            comment.save()
            return render(request, 'maps/comment_complete.html')
    
    else:
        print("comment get 들어옴")
        form = CommentForm()
        context = {
            'form' : form,
            'review_pk' : review_pk,
            'comment_user_pk' : comment_user_pk,
            'review' : review,
        }
        print(form)
    
    return render(request, 'maps/comment_create.html',context)



def comment_complete(request):
    return render(request, 'maps/comment_complete.html')


def review_all(request):
    reviews = Review.objects.all()
    # paginator = Paginator(reviews, 12)
    
    # page_number = request.GET.get('page')
    # reviews = paginator.get_page(page_number)
    # for star in len(reviews.food_star):
    

    context = {
        'reviews' : reviews,
    }
    return render(request, 'maps/review_all.html', context)

foother/maps/templates/maps/review_create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
<style>
    .wrap {position: absolute;left: 0;bottom: 40px;width: 450px;height: 300px;margin-left: -144px;text-align: left;overflow: hidden;font-size: 10px;font-family: 'Malgun Gothic', dotum, '돋움', sans-serif;line-height: 1.5;}
    .wrap * {padding: 0;margin: 0;}
    .wrap .info {width: 286px;height: 120px;border-radius: 5px;border-bottom: 2px solid #ccc;border-right: 1px solid #ccc;overflow: hidden;background: #fff;}
    .wrap .info:nth-child(1) {border: 0;box-shadow: 0px 1px 2px #888;}
    .info .title {padding: 5px 0 0 10px;height: 30px;background: #eee;border-bottom: 1px solid #ddd;font-size: 15px;font-weight: bold;}
    .info .close {position: absolute;top: 10px;right: 10px;color: #888;width: 17px;height: 17px;background: url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/overlay_close.png');}
    .info .close:hover {cursor: pointer;}
    .info .body {position: relative;overflow: hidden;background-color: white;}
    .info .desc {position: relative;margin: 13px 0 0 90px;height: 75px;}
    .desc .ellipsis {overflow: hidden;text-overflow: ellipsis;white-space: nowrap;}
    .desc .jibun {font-size: 9px;color: #888;margin-top: -2px;}
    .info .img {position: absolute;top: 6px;left: 5px;width: 73px;height: 71px;border: 1px solid #ddd;color: #888;overflow: hidden;}
    .info:after {content: '';position: absolute;margin-left: -12px;left: 50%;bottom: 0;width: 22px;height: 12px;background: url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/vertex_white.png')}
    .info .link {color: #5085BB;}
</style>

<div class="container3">
  <h1><img src="{% static 'img/nav/upload.png' %}" class="page-icon mr-2 ml-2">리뷰작성</h1>
  <div class="upload-container">
    <label for="addressSearch">주소 검색 : <input id="addressSearch" type="text"></label>
    <input id="searchBtn" type="submit" class="mb-3">
    <div id="map" style="width:500px;height:400px;" class="mb-3"></div>

    <form action="{% url 'maps:review-create' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-success">작성</button>
    </form>
  </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  // 검색을 위한 돔 객체 생성
  var addressSearch = document.getElementById('addressSearch')
  var searchBtn = document.getElementById('searchBtn')
  var overlay
  var deleteflag = true
  var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = {

      center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표
      //center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표
      level: 4 // 지도의 확대 레벨
    };

  // 지도를 생성합니다.
  var map = new kakao.maps.Map(mapContainer, mapOption);


  // 주소검색 버튼 클릭
  searchBtn.addEventListener('click', function (event) {

    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(showPosition);
    }
    
    function showPosition(position) {
      //x.innerHTML="위도: " + position.coords.latitude + "<br />경도: " + position.coords.longitude;   
      var latitude = position.coords.latitude
      var longtitude = position.coords.longitude

      console.log(latitude)
      console.log(longtitude)

      axios.get('https://dapi.kakao.com/v2/local/search/keyword.json?y=' + longtitude + '&x=' + latitude, {
        params: {
          query: addressSearch.value,
          category_group_code: 'FD6',
          page: 10
        },
        headers: {
          'Authorization': 'KakaoAK 1bdcfbeb6bb8e3bf27b8caf11c8e53b4'
        }
      }).then(function (res) {


        // 요청이 성공했을 때 실행하는 함수
        // res에 가게이름, 좌표, 주소 포함 Json 데이터로 받아옴.

        //중심좌표를 위한 위도, 경도 설정
        var lat = res.data.documents[0].x
        var lng = res.data.documents[0].y
        console.log(res.data)
        // 지도 및 마커 영역
        // 마커를 클릭하면 장소명을 표출할 인포윈도우 입니다
        var infowindow = new kakao.maps.InfoWindow({
          zIndex: 1
        });

        var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
          mapOption = {

            center: new kakao.maps.LatLng(longtitude, latitude), // 지도의 중심좌표
            //center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표
            level: 6 // 지도의 확대 레벨
          };

        // 지도를 생성합니다.
        var map = new kakao.maps.Map(mapContainer, mapOption);

        // 장소 검색 객체를 생성합니다
        var ps = new kakao.maps.services.Places();

        // 키워드로 장소를 검색합니다
        ps.keywordSearch(addressSearch.value, placesSearchCB, {
          location: new kakao.maps.LatLng(latitude, longtitude)
        });
      
        // 키워드 검색 완료 시 호출되는 콜백함수 입니다
        function placesSearchCB(data, status, pagination) {
          if (status === kakao.maps.services.Status.OK) {

            // 검색된 장소 위치를 기준으로 지도 범위를 재설정하기위해
            // LatLngBounds 객체에 좌표를 추가합니다
            var bounds = new kakao.maps.LatLngBounds();

            for (var i = 0; i < data.length; i++) {
              displayMarker(data[i]);
              bounds.extend(new kakao.maps.LatLng(data[i].y, data[i].x));
              console.log(data[i].road_address_name)
            }
            // 검색된 장소 위치를 기준으로 지도 범위를 재설정합니다
            map.setBounds(bounds);
          }
        }
        function closeOverlay(){
          overlay.setMap(null);
          flag=false;
        }
        
        // 지도에 마커를 표시하는 함수입니다
        function displayMarker(place) {
          console.log("hhhhh")
          // 마커를 생성하고 지도에 표시합니다
          var marker = new kakao.maps.Marker({
            map: map,
            position: new kakao.maps.LatLng(place.y, place.x)
          });


          // 커스텀 오버레이를 닫기 위해 호출되는 함수입니다 
          

          // 마커에 클릭이벤트를 등록합니다
          // var flag = false;
          //if(flag==false){
            kakao.maps.event.addListener(marker, 'click', function () {
              if(deleteflag == false){
                closeOverlay();
                deleteflag = true
              }
              else{
                  // 마커를 클릭하면 장소명이 인포윈도우에 표출됩니다
                var content = '<div style="wrap">' +
                  '<div class="info">' +
                  '<div class="title">' + place.place_name +
                  '<div id="close" class="close"  title="닫기"></div>' +
                  '</div>' +
                  '<div class="body">' +
                  '<div class="img">' +
                  '<img src="https://www.pngrepo.com/png/184695/180/restaurant-plate.png" width="73" height="70">' +
                  '</div>' +
                  '<div class="desc">' +
                  '<div class="ellipsis">' + place.road_address_name + '</div>' +
                  '<div class="jibun ellipsis">' + place.category_name + '</div>' +
                  '<div class="jibun ellipsis">' + place.phon + '</div>' +
                  '<a href="https://place.map.kakao.com/' + res.data.documents[0].id +
                  '"target="_blank">음식점 자세히 보기</a>' +
                  '</div>' +
                  '</div>' + '</div>' + '</div>';
                console.log(content)
                // 마커 위에 커스텀오버레이를 표시합니다
                // 마커를 중심으로 커스텀 오버레이를 표시하기위해 CSS를 이용해 위치를 설정했습니다
                overlay = new kakao.maps.CustomOverlay({
                  content: content,
                  map: map,
                  position: marker.getPosition()
                });                 
                  overlay.setMap(map);
                  deleteflag = false;

                closeBtn = document.getElementById("close")
                      
                
                closeBtn.addEventListener("click", closeOverlay)
                //infowindow.open(map, marker);
                console.log(place)
                // 리뷰로 올릴 위도 설정
                var lat = document.querySelector('#id_lat')
                lat.value = place.y;

                // 리뷰로 올릴 경도 설정
                var lng = document.querySelector('#id_lng')
                lng.value = place.x;

                //리뷰로 올릴 음식점 이름 설정
                var restaurant_name = document.querySelector('#id_restaurant_name')
                restaurant_name.value = place.place_name

                //리뷰로 올릴 음식점 주소 설정
                var restaurant_address = document.querySelector('#id_restaurant_address')
                restaurant_address.value = place.road_address_name
                }

              });
          //}
          

        }

     // function closeOverlay() {
      //      overlay.setMap(null);
      //    } 

      })
    }
  })
</script>


{% endblock %}

foother/maps/templates/maps/review_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
<style>
    .wrap {position: absolute;left: 0;bottom: 40px;width: 450px;height: 300px;margin-left: -144px;text-align: left;overflow: hidden;font-size: 12px;font-family: 'Malgun Gothic', dotum, '돋움', sans-serif;line-height: 1.5;}
    .wrap * {padding: 0;margin: 0;}
    .wrap .info {width: 286px;height: 120px;border-radius: 5px;border-bottom: 2px solid #ccc;border-right: 1px solid #ccc;overflow: hidden;background: #fff;}
    .wrap .info:nth-child(1) {border: 0;box-shadow: 0px 1px 2px #888;}
    .info .title {padding: 5px 0 0 10px;height: 30px;background: #eee;border-bottom: 1px solid #ddd;font-size: 18px;font-weight: bold;}
    .info .close {position: absolute;top: 10px;right: 10px;color: #888;width: 17px;height: 17px;background: url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/overlay_close.png');}
    .info .close:hover {cursor: pointer;}
    .info .body {position: relative;overflow: hidden;background-color: white;}
    .info .desc {position: relative;margin: 13px 0 0 90px;height: 75px;}
    .desc .ellipsis {overflow: hidden;text-overflow: ellipsis;white-space: nowrap;}
    .desc .jibun {font-size: 11px;color: #888;margin-top: -2px;}
    .info .img {position: absolute;top: 6px;left: 5px;width: 73px;height: 71px;border: 1px solid #ddd;color: #888;overflow: hidden;}
    .info:after {content: '';position: absolute;margin-left: -12px;left: 50%;bottom: 0;width: 22px;height: 12px;background: url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/vertex_white.png')}
    .info .link {color: #5085BB;}
</style>

<div class="container3">
  <h1><img src="{% static 'img/nav/upload.png' %}" class="page-icon mr-2 ml-2">리뷰수정</h1>
  <div class="upload-container">
    <label for="addressSearch">주소 검색 : <input id="addressSearch" type="text"></label>
    <input id="searchBtn" type="submit" class="mb-3">
    <div id="map" style="width:500px;height:400px;" class="mb-3"></div>

    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-success">수정</button>
    </form>
  </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  // 검색을 위한 돔 객체 생성
  var addressSearch = document.getElementById('addressSearch')
  var searchBtn = document.getElementById('searchBtn')
  var overlay
  var deleteflag = true
  var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = {

      center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표
      //center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표
      level: 4 // 지도의 확대 레벨
    };

  // 지도를 생성합니다.
  var map = new kakao.maps.Map(mapContainer, mapOption);


  // 주소검색 버튼 클릭
  searchBtn.addEventListener('click', function (event) {

    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(showPosition);
    }
    
    function showPosition(position) {
      //x.innerHTML="위도: " + position.coords.latitude + "<br />경도: " + position.coords.longitude;   
      var latitude = position.coords.latitude
      var longtitude = position.coords.longitude

      console.log(latitude)
      console.log(longtitude)

      axios.get('https://dapi.kakao.com/v2/local/search/keyword.json?y=' + longtitude + '&x=' + latitude, {
        params: {
          query: addressSearch.value,
          category_group_code: 'FD6',
          page: 10
        },
        headers: {
          'Authorization': 'KakaoAK 1bdcfbeb6bb8e3bf27b8caf11c8e53b4'
        }
      }).then(function (res) {


        // 요청이 성공했을 때 실행하는 함수
        // res에 가게이름, 좌표, 주소 포함 Json 데이터로 받아옴.

        //중심좌표를 위한 위도, 경도 설정
        var lat = res.data.documents[0].x
        var lng = res.data.documents[0].y
        console.log(res.data)
        // 지도 및 마커 영역
        // 마커를 클릭하면 장소명을 표출할 인포윈도우 입니다
        var infowindow = new kakao.maps.InfoWindow({
          zIndex: 1
        });

        var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
          mapOption = {

            center: new kakao.maps.LatLng(longtitude, latitude), // 지도의 중심좌표
            //center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표
            level: 6 // 지도의 확대 레벨
          };

        // 지도를 생성합니다.
        var map = new kakao.maps.Map(mapContainer, mapOption);

        // 장소 검색 객체를 생성합니다
        var ps = new kakao.maps.services.Places();

        // 키워드로 장소를 검색합니다
        ps.keywordSearch(addressSearch.value, placesSearchCB, {
          location: new kakao.maps.LatLng(latitude, longtitude)
        });
      
        // 키워드 검색 완료 시 호출되는 콜백함수 입니다
        function placesSearchCB(data, status, pagination) {
          if (status === kakao.maps.services.Status.OK) {

            // 검색된 장소 위치를 기준으로 지도 범위를 재설정하기위해
            // LatLngBounds 객체에 좌표를 추가합니다
            var bounds = new kakao.maps.LatLngBounds();

            for (var i = 0; i < data.length; i++) {
              displayMarker(data[i]);
              bounds.extend(new kakao.maps.LatLng(data[i].y, data[i].x));
              console.log(data[i].road_address_name)
            }
            // 검색된 장소 위치를 기준으로 지도 범위를 재설정합니다
            map.setBounds(bounds);
          }
        }
        function closeOverlay(){
          overlay.setMap(null);
          flag=false;
        }
        
        // 지도에 마커를 표시하는 함수입니다
        function displayMarker(place) {
          console.log("hhhhh")
          // 마커를 생성하고 지도에 표시합니다
          var marker = new kakao.maps.Marker({
            map: map,
            position: new kakao.maps.LatLng(place.y, place.x)
          });


          // 커스텀 오버레이를 닫기 위해 호출되는 함수입니다 
          

          // 마커에 클릭이벤트를 등록합니다
          // var flag = false;
          //if(flag==false){
            kakao.maps.event.addListener(marker, 'click', function () {
              if(deleteflag == false){
                closeOverlay();
                deleteflag = true
              }
              else{
                  // 마커를 클릭하면 장소명이 인포윈도우에 표출됩니다
                var content = '<div style="wrap">' +
                  '<div class="info">' +
                  '<div class="title">' + place.place_name +
                  '<div id="close" class="close"  title="닫기"></div>' +
                  '</div>' +
                  '<div class="body">' +
                  '<div class="img">' +
                  '<img src="https://www.pngrepo.com/png/184695/180/restaurant-plate.png" width="73" height="70">' +
                  '</div>' +
                  '<div class="desc">' +
                  '<div class="ellipsis">' + place.road_address_name + '</div>' +
                  '<div class="jibun ellipsis">' + place.category_name + '</div>' +
                  '<div class="jibun ellipsis">' + place.phon + '</div>' +
                  '<a href="https://place.map.kakao.com/' + res.data.documents[0].id +
                  '"target="_blank">음식점 자세히 보기</a>' +
                  '</div>' +
                  '</div>' + '</div>' + '</div>';
                console.log(content)
                // 마커 위에 커스텀오버레이를 표시합니다
                // 마커를 중심으로 커스텀 오버레이를 표시하기위해 CSS를 이용해 위치를 설정했습니다
                overlay = new kakao.maps.CustomOverlay({
                  content: content,
                  map: map,
                  position: marker.getPosition()
                });                 
                  overlay.setMap(map);
                  deleteflag = false;

                closeBtn = document.getElementById("close")
                      
                
                closeBtn.addEventListener("click", closeOverlay)
                //infowindow.open(map, marker);
                console.log(place)
                // 리뷰로 올릴 위도 설정
                var lat = document.querySelector('#id_lat')
                lat.value = place.y;

                // 리뷰로 올릴 경도 설정
                var lng = document.querySelector('#id_lng')
                lng.value = place.x;

                //리뷰로 올릴 음식점 이름 설정
                var restaurant_name = document.querySelector('#id_restaurant_name')
                restaurant_name.value = place.place_name

                //리뷰로 올릴 음식점 주소 설정
                var restaurant_address = document.querySelector('#id_restaurant_address')
                restaurant_address.value = place.road_address_name
                }

              });
          //}
          

        }

     // function closeOverlay() {
      //      overlay.setMap(null);
      //    } 

      })
    }
  })
</script>


{% endblock %}