foother/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/<str:username>', views.update, name='update'),
    path('<str:username>/', views.detail, name='detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/<str:username>/', views.follow, name='follow'),
]

foother/foother/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.foother_index, name='foother-index'),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('maps.urls')),
    path('foods/', include('foods.urls')),
    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foother/maps/urls.py
from django.urls import path
from . import views


app_name = 'maps'


urlpatterns = [
    path('all/', views.review_all, name='review-all'),
    path('create/', views.review_create, name='review-create'),
    path('<str:username>/<int:review_pk>/', views.review_detail, name='review-detail'),
    path('<int:review_pk>/update/', views.review_update, name='review-update'),
    path('<int:review_pk>/like/', views.like, name='like'),
    path('<str:comment_user_pk>/<int:review_pk>/comment/create/', views.comment_create, name='comment-create'),
    path('<str:comment_username>/<int:review_pk>/comment/complete/', views.comment_complete, name='comment-complete'),
]

foother/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings


class User(AbstractUser):
    user_phone = models.CharField(max_length=13)
    user_created = models.DateTimeField(auto_now_add=True)
    user_score = models.IntegerField(default=0)
    user_profile_image = ProcessedImageField(
                    upload_to = 'user_profile_image',
                    processors=[ResizeToFill(500, 500)],
                    format='JPEG',
                    options={
                        'quality': 70},
                    default='default.png'
    )
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

    user_intro = models.CharField(max_length=40)
    # class Meta:
    #     ordering = ['-score']
    

foother/maps/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class Review(models.Model):
    # hidden
    lat = models.FloatField()
    lng = models.FloatField()
    restaurant_address = models.CharField(max_length=30)

    # TextInput_readonly
    restaurant_name = models.CharField(max_length=30)

    # TextInput
    food_name = models.CharField(max_length=30)
    
    # Textarea
    food_review = models.CharField(max_length=30)
    
    #손봐야할 거
    food_star = models.IntegerField()

    food_image = ProcessedImageField(
                upload_to='upload_photo',
                processors=[ResizeToFill(200, 200)],
                format='JPEG',
                options={
                    'quality': 80}
    )
    
    visit_date = models.DateField(auto_now_add=False)

    food_kind = models.CharField(max_length=10)

    # ForeignKey
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    
    class Meta:
        ordering = ['-id']


class Comment(models.Model):
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='which_review')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='which_user')

    class Meta:
        ordering = ['-created_at']

foother/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import User
from django import forms
from django.forms.widgets import SelectDateWidget


class CustomUserCreationForm(UserCreationForm):
    user_phone = forms.CharField(
        label = '핸드폰 번호:',
        widget = forms.TextInput(
            attrs = {
                'class' : 'my-user-phone form-control',
                'placeholder' : '핸드폰번호를 입력해주세요', 
            }
        )
    )
    user_info = forms.CharField(
        label = '소개 한줄:',
        widget = forms.Textarea(
            attrs = {
                'class' : 'my-user-info form-control',
                'placeholder' : '자기소개를 살짝 적어주세요',
                'rows' : 3,
                'cols' : 5,
            }
        )
    )


    
    # 원래라면  forms.ModelForm
    # 내가 어떤 유저 모델을 가르키고 있는지를 알고 있어야 한다.
    # AUTH_USER_MODEL
    class Meta:
        model = get_user_model()
        fields = ('username',  'password1',  'password2', 'user_phone', 'user_profile_image')

# '%Y-%m-%d'

foother/accounts/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from .models import User
from .forms import CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

User = get_user_model()

def user_ranking():
    User = get_user_model()
    users = User.objects.all()
    if len(users) >3:
        while len(users) == 3:
            del users[-1]
    
    ranking = {
        'ranking' : users,
    }
    # return User.objects.all()
    return ranking
    # rankings = user_ranking()


def signup(request):
    rankings = user_ranking()
    if request.user.is_authenticated :
        return redirect('foother-index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('maps:review-all')

    else:
        form = CustomUserCreationForm()
    
    context = {
        'form' : form,
        'rankings' : rankings
    }

    return render(request, 'accounts/form.html', context)


def login(request):
    rankings = user_ranking()
    if request.user.is_authenticated:
        return redirect('foother-index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            # user = form.save()
            user = form.get_user()
            auth_login(request, user)
            return redirect('maps:review-all')

    else:
        form = AuthenticationForm()
    
    context = {
        'form' : form,
        'rankings' : rankings,
    }

    return render(request, 'accounts/form.html', context)


@login_required
def detail(request, username):
    rankings = user_ranking()
    user = User.objects.get(username=username)

    context = {
        'user' : user,
        'rankings' : rankings,
    }
    return render(request, 'accounts/detail.html', context)


@login_required
def update(request, username):
    rankings = user_ranking()
    user = get_object_or_404(User, username=username)
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect ('accounts:profile', user.username)
    else:
        form = CustomUserCreationForm(instance=user)
    
    context = {
        'form' : form,
        'rankings' : rankings,
    }

    return render(request, 'accounts/update.html', context)


def logout(request):
    auth_logout(request)
    return redirect('foother-index')



def profile(request, username):
    rankings = user_ranking()
    if request.user.is_authenticated:
        user = get_object_or_404(get_user_model(), username=username)
        context = {
            'user_profile' : user,
            'rankings' : rankings,
        }
    else:
        return redirect('foother-index')
        
    return render(request, 'accounts/profile.html', context)


@login_required
def follow(request, username):
    you = get_object_or_404(User, username=username)
    me = request.user
    if me != you:
        if you.followers.filter(username=me.username).exists():
            you.followers.remove(me)
        else:
            you.followers.add(me)
    return redirect('accounts:profile', you.username)

foother/accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block content %}
    <table>
        <tr>
            <td>이름</td>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <td>핸드폰번호</td>
            <td>{{ user.user_phone }}</td>
        </tr>
        <tr>
            <td>현재점수</td>
            <td>{{ user.user_score }}점</td>
        </tr>
        <tr>
            <td>생일 </td>
            <td>{{ user.user_birth }}</td>
        </tr>
    </table>
    <a class="d-block" href="{{ user.user_profile_image.url }}">프로필 사진:</a>
    <img class="d-block" src="{{ user.user_profile_image.url }}">
    <a class="btn btn-warning" href="{% url 'accounts:update' user.username %}">개인정보 수정하기</a>
    <a class="btn btn-primary" href="{% url 'foother-index' %}">뒤로가기</a>
{% endblock  %}

foother/accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
    {% comment %} {% if request.resolver_match.url_name == 'signup' %}
        <h1>회원가입</h1>
    {% else  %}
        <h1>로그인</h1>
    {% endif %} {% endcomment %}
{% if request.resolver_match.url_name == 'signup' %}
    <h1><img src="{% static 'img/title/purple.png' %}" class="title-icon mr-2 ml-2 mt-4">회원가입</h1>
{% else  %}
    <h1><img src="{% static 'img/title/green.png' %}" class="title-icon mr-2 ml-2 mt-4">로그인</h1>
{% endif %}

<div class="container3">
   <form action="" method="POST" enctype="multipart/form-data">
        {% if request.resolver_match.url_name == 'signup' %}
            <div class="user-sign-container">
        {% else  %}
            <div class="user-login-container">
        {% endif %}
                <!-- 하나의 파일에서 두개의 기능 -->
            {% csrf_token %}
            {% bootstrap_form form %}
                <button class="btn btn-success">
                    {% if request.resolver_match.url_name == 'signup' %}
                        회원가입
                    {% else  %}
                        로그인
                    {% endif %}
                </button>
            </div>
    </form>
</div>

{% endblock  %}

foother/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
 
{% block content %}
<!--fontawsome-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.1/css/all.css" integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q" crossorigin="anonymous">
<div class="container2 mt-5 mb-5 d-flex justify-content-center">
  <div class="row align-items-center">
    <div class="col-4">
      <div class="row">
        <img class="col-10 rounded-circle " src="{{ user_profile.user_profile_image.url }}">
      </div>
    </div>
    <div class="col-8">
        <h1 class="text-left d-inline">{{ user_profile.username }}</h1><span class="d-inline ml-4" style="font-size:1.2rem"><i class="fas fa-crown fa-lg mr-2" style="color:#f5da42"></i>{{ user_profile.review_set.count }}점</span>
        <a href="{% url 'accounts:update' user.username %}" class="d-inline ml-5">
        {% if request.user == user_profile %}
          <button class="d-inline ml-3 mr-4 profile-button"><i class="fas fa-cog fa-lg mr-2" style="color:#b8b6b6"></i>프로필 편집</button></a>
        {% endif %}
        <div class="d-inline">
          {% if request.user != user_profile %}
            {% if request.user in user_profile.followers.all %}
              <a href="{% url 'accounts:follow' user_profile.username %}" class="btn btn-follow btn-lg btn-block mt-2">UNFOLLOW</a>
            {% else %}
              <a href="{% url 'accounts:follow' user_profile.username %}" class="btn btn-follow btn-lg btn-block mt-2">FOLLOW</a>
            {% endif %}
          {% endif %}
        </div>

        <div class="d-flex flex-row justify-content-start mt-3">
            <div class="mr-5">
              <a class="d-block">게시물</a>
              <a class="ml-2 font-bold">{{ user_profile.review_set.count }}</a>
            </div>

            <div class="ml-5 mr-5">
              <a class="d-block">팔로워</a>
              <a class="ml-2 font-bold">{{ user_profile.followers.count }}</a>
            </div>

            <div class="ml-5 mr-5">
              <a class="d-block">팔로잉</a>
              <a class="ml-2 font-bold">{{ user_profile.followings.count }}</a>
            </div>
        </div>

        <div class="d-block mt-3">
              <span>{{ user_profile.user_intro }}</span>  
        </div>
        
        <hr class="my-4">
        
        
        <div class="row no-gutters justify-content-around">
          {% comment %} <form action="{% url 'accounts:delete' %}" method="POST" class="col-4">
            {% csrf_token %}
            <button class="btn btn-danger btn-lg btn-block mt-2">회원탈퇴</button>
          </form> {% endcomment %}
        </div>

      
    </div>
  </div>
</div>



  <div class="container mt-5">
    <div class="row-cols-3 portfolio-container">
      {% for review in user_profile.review_set.all %}
        <div class="col-md-4 portfolio-item filter-app mb-4">
          <a href="{% url 'maps:review-detail' request.user review.pk %}"><img src="{{ review.food_image.url }}" class="review-image"></a>
        </div>
      {% endfor %}
    </div>
  </div>



{% endblock  %}

foother/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block content %}
<div class="user-sign-container">
    <h1><img src="{% static 'img/title/orange.png' %}" class="title-icon mr-2 ml-2">사용자 정보 수정</h1>
    <form action="{% url 'accounts:update' user.username %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary">개인정보 수정하기</button>
    </form>
</div>
{% endblock  %}