foother/foods/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'foods'

urlpatterns = [
    path('result/<str:food_ctg>/', views.result, name='result'),
    path('result/', views.hangover, name='hangover'),
    path('select/<str:food_name>/', views.select, name='select'),
]

foother/foother/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.foother_index, name='foother-index'),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('maps.urls')),
    path('foods/', include('foods.urls')),
    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foother/maps/urls.py
from django.urls import path
from . import views


app_name = 'maps'


urlpatterns = [
    path('all/', views.review_all, name='review-all'),
    path('create/', views.review_create, name='review-create'),
    path('<str:username>/<int:review_pk>/', views.review_detail, name='review-detail'),
    path('<int:review_pk>/update/', views.review_update, name='review-update'),
    path('<int:review_pk>/like/', views.like, name='like'),
    path('<str:comment_user_pk>/<int:review_pk>/comment/create/', views.comment_create, name='comment-create'),
    path('<str:comment_username>/<int:review_pk>/comment/complete/', views.comment_complete, name='comment-complete'),
]

foother/foods/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


# Create your models here.
class FoodCategory(models.Model):
    food_ctg = models.CharField(max_length=100)

    food_ctg_image = ProcessedImageField(
                upload_to='food_ctg_photo',
                processors=[ResizeToFill(200, 200)],
                format='JPEG',
                options={
                    'quality': 80},
    )
    # selectbox로 설정
    # img = models.ImageField()
    # food_set 자동생김    


class FoodChoice(models.Model):
    food_name = models.CharField(max_length=100)
    food_ctgs = models.ForeignKey(FoodCategory, on_delete=models.CASCADE)
    # food_by_emotion
    status = models.CharField(max_length=50,default="일반")

foother/foods/forms.py
from django import forms
from .models import FoodCategory, FoodChoice


class FoodCategoryForm(forms.ModelForm):
     class Meta:
         model = FoodCategory


class FoodChoiceForm(forms.ModelForm):
     class Meta:
         model = FoodChoice

foother/foods/views.py
from django.shortcuts import render
from .models import FoodCategory, FoodChoice
import random
from django.contrib.auth import get_user_model


def user_ranking():
    User = get_user_model()
    users = User.objects.all()
    if len(users) >3:
        while len(users) == 3:
            del users[-1]
    
    ranking = {
        'ranking' : users,
    }
    # return User.objects.all()
    return ranking
    # rankings = user_ranking()


def result(request, food_ctg):
    rankings = user_ranking()
    foodCategory = FoodCategory.objects.get(food_ctg=food_ctg)
    foods = foodCategory.foodchoice_set.all()
    randomfood = random.choice(foods)
    # emotion에 pk가 emotion_id인 emotion을 가지고 온다.
    # 그 emotion에 음식 세트를 모두 가져온다.
    context = {
        'foods' : foods,
        'randomfood' : randomfood,
        'foodCategory' : foodCategory,
        'rankings' : rankings,
    }
    print(foodCategory.foodchoice_set)
    return render(request,'foods/food_result.html', context)
    # 예상 food.emotion_


def hangover(request):
    rankings = user_ranking()
    foods = FoodChoice.objects.filter(status='해장')
    randomfood = random.choice(foods) 
    context = {
        'foods' : foods,
        'randomfood' : randomfood,
        'rankings' : rankings,
    }
    return render(request,'foods/food_result.html', context)


def select(request, food_name):
    rankings = user_ranking()
    food = FoodChoice.objects.get(food_name=food_name)
    context = {
        'food' : food,
        'rankings' : rankings,
    }
    return render(request, 'foods/food_select.html', context)
   

# def example(request):
#     return render(request, 'foods/example.html')

foother/foods/templates/foods/food_hangover.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col">
    {% for food in foods %}
        <a href="{% url 'foods:select' food.food_name %}"><button class="btn btn-succerss">{{ food.food_name }}</button></a>
    {% endfor %}
    </div>
</div>
<br>
<div class="row">
    <div class="col">
        <button class="btn btn-warning" onclick="randomMenu()"> 오늘 이 음식은 어때요? </button>
        <a href="{% url 'foods:select' randomfood.food_name %}">
        <span id="menu"></span>
        </a>
    </div>
</div>
<script>
    var flag = true;
    function randomMenu(){
        if(flag == true){
            flag = false
            var target = document.getElementById('menu') 
            result = '{{ randomfood.food_name }}'
            target.innerHTML = result
        }
        else{
            flag = true
            var target = document.getElementById('menu') 
            result = ""
            target.innerHTML = result
        }
    }
</script>
{% endblock %}

foother/foods/templates/foods/food_main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    

 
 <div class="container3">
 <h1 class="mb-3 font-bold"><img src="{% static 'img/nav/foodrec.png' %}" class="page-icon mr-2 ml-2">음식추천</h1>     
 <h2 class="mt-1 mb-3 ml-3 font-bold"><img src="{% static 'img/title/green.png' %}" class="title-icon mr-2 ml-2">1단계: 음식 카테고리 선택</h2>     
    <div class="container d-flex justify-content-center mt-3" style="width:60%">
        <div class="row">
        {% for foodCategory in foodsCategories %}
            <div class="col-4 food-ctg-box mb-3">
                <a href="{% url 'foods:result' foodCategory.food_ctg %}"><img src="{{ foodCategory.food_ctg_image.url }}" class="img-square"></a>
            {% comment %} <button class="btn btn-success">{{ foodCategory.food_ctg }}</button> {% endcomment %}
            </div>
        {% endfor %}
            <div class="col-4 food-ctg-box mb-3">
                <a href="{% url 'foods:hangover' %}"><img src="{% static 'img/ctg/hangover.png' %} " class="img-square"></a>
            </div>
        </div>
    </div>
</div>

    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script>
        {% comment %} var feelingButtons = document.querySelectorAll('.attr')
        feelingButtons.forEach(function(feelingButton){
             feelingButton.addEventListener('click', function(event){
                var targetId = event.target.dataset.id;
                console.log(event.target.dataset.id);
                axios.get(`/mains/${targetId}/`)
                .then(function(res){
                    console.log(res.data.foods)
                    var result = document.getElementById('menu');
                    for (var food in res.data.foods) { 
                        result.innetHTML += "<li>"+food+"</li>";
                    }
                })
             });
        }); {% endcomment %}
    </script>
{% endblock %}

foother/foods/templates/foods/food_result.html
  
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <div class="container3">
 <h1 class="mb-3 font-bold"><img src="{% static 'img/nav/foodrec.png' %}" class="page-icon mr-2 ml-2">음식추천</h1>     
    <h2 class="mt-1 mb-3 ml-3 font-bold"><img src="{% static 'img/title/orange.png' %}" class="title-icon mr-2 ml-2">2단계:
        <span class="ml-3 mr-1" style="color:#f59a38">"
        {% if request.resolver_match.url_name == 'hangover'  %}
        해장
        {% else %}
        {{ foodCategory.food_ctg }}
        {% endif %}
        "</span> 종류 골라보기
    </h2>     
        <div class="container d-flex justify-content-center mt-5 mb-5" >
            <div class="row col-3">
                <div class="d-flex align-items-center justify-content-center">
                {% if request.resolver_match.url_name == 'hangover'  %}
                    <img src="{% static 'img/ctg/hangover.png' %}" style="width:100%">
                {% else %}
                    <img src="{{ foodCategory.food_ctg_image.url }}" style="width:100%;">
                {% endif %}
                </div>
            </div>
            <div class="row col-9">
                {% for food in foods %}
                    <div class="col-4 food-ctg-box mb-3">
                        <a href="{% url 'foods:select' food.food_name %}"><button class="btn btn-succerss font-bold"><h3>{{ food.food_name }}</h3></button></a>
                    </div>
                {% endfor %}
            </div>
        </div>
</div>


<div class="container3">
    <div class="container d-flex justify-content-center" style="width:70%">
        <div class="row">
            <div class="col-5">
                <button onclick="randomMenu()" class="food-result"> 
                    <img src="{% static 'img/nav/random.png' %}" style="width:100%" class="d-block"> 
                </button>
            </div>
            <div class="col-4 d-flex flex-column justify-content-center">
                <a href="{% url 'foods:select' randomfood.food_name %}" style="color:black">
                    <h3 id="menu"></h3>
                </a>
            </div>
        </div>
    </div>
</div>

<div class="container3">
    <div class="row">
        <div class="col-10">
            <dvi class="d-flex justify-content-end">
                <a href="{% url 'foother-index' %}" style="color:black"><h5><i class="fas fa-backward fa-md mr-2" style="color:black; opacity:0.7"></i>1단계 다시하기</h5></a>
            </dvi>
        </div>
    </div>
</div>

<script>
    var flag = true;
    function randomMenu(){
        if(flag == true){
            flag = false
            var target = document.getElementById('menu') 
            result = '{{ randomfood.food_name }}'
            target.innerHTML = result
        }
        else{
            flag = true
            var target = document.getElementById('menu') 
            result = ""
            target.innerHTML = result
            location.reload(true);
        }
    }
</script>
{% endblock %}